/*
 * AccountAndTransactionAPISpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.co.middleware.apicentre.apinomatls.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * AccountSubTypeEnum to be used.
 */
public enum AccountSubTypeEnum {
    CHARGECARD,

    CREDITCARD,

    CURRENTACCOUNT,

    EMONEY,

    LOAN,

    MORTGAGE,

    PREPAIDCARD,

    SAVINGS;


    private static TreeMap<String, AccountSubTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        CHARGECARD.value = "ChargeCard";
        CREDITCARD.value = "CreditCard";
        CURRENTACCOUNT.value = "CurrentAccount";
        EMONEY.value = "EMoney";
        LOAN.value = "Loan";
        MORTGAGE.value = "Mortgage";
        PREPAIDCARD.value = "PrePaidCard";
        SAVINGS.value = "Savings";

        valueMap.put("ChargeCard", CHARGECARD);
        valueMap.put("CreditCard", CREDITCARD);
        valueMap.put("CurrentAccount", CURRENTACCOUNT);
        valueMap.put("EMoney", EMONEY);
        valueMap.put("Loan", LOAN);
        valueMap.put("Mortgage", MORTGAGE);
        valueMap.put("PrePaidCard", PREPAIDCARD);
        valueMap.put("Savings", SAVINGS);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static AccountSubTypeEnum constructFromString(String toConvert) throws IOException {
        AccountSubTypeEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static AccountSubTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of AccountSubTypeEnum values to list of string values.
     * @param toConvert The list of AccountSubTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<AccountSubTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (AccountSubTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 