/*
 * AccountAndTransactionAPISpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.co.middleware.apicentre.apinomatls.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AccountAccessConsentResponse type.
 */
public class AccountAccessConsentResponse {
    private AccountAccessConsentResponseModel data;
    private Risk risk;
    private Links links;
    private Meta meta;

    /**
     * Default constructor.
     */
    public AccountAccessConsentResponse() {
    }

    /**
     * Initialization constructor.
     * @param  data  AccountAccessConsentResponseModel value for data.
     * @param  risk  Risk value for risk.
     * @param  links  Links value for links.
     * @param  meta  Meta value for meta.
     */
    public AccountAccessConsentResponse(
            AccountAccessConsentResponseModel data,
            Risk risk,
            Links links,
            Meta meta) {
        this.data = data;
        this.risk = risk;
        this.links = links;
        this.meta = meta;
    }

    /**
     * Getter for Data.
     * @return Returns the AccountAccessConsentResponseModel
     */
    @JsonGetter("Data")
    public AccountAccessConsentResponseModel getData() {
        return data;
    }

    /**
     * Setter for Data.
     * @param data Value for AccountAccessConsentResponseModel
     */
    @JsonSetter("Data")
    public void setData(AccountAccessConsentResponseModel data) {
        this.data = data;
    }

    /**
     * Getter for Risk.
     * The Risk section is sent by the initiating party to the API Provider. It is used to specify
     * additional details for risk scoring.
     * @return Returns the Risk
     */
    @JsonGetter("Risk")
    public Risk getRisk() {
        return risk;
    }

    /**
     * Setter for Risk.
     * The Risk section is sent by the initiating party to the API Provider. It is used to specify
     * additional details for risk scoring.
     * @param risk Value for Risk
     */
    @JsonSetter("Risk")
    public void setRisk(Risk risk) {
        this.risk = risk;
    }

    /**
     * Getter for Links.
     * Links relevant to the payload
     * @return Returns the Links
     */
    @JsonGetter("Links")
    public Links getLinks() {
        return links;
    }

    /**
     * Setter for Links.
     * Links relevant to the payload
     * @param links Value for Links
     */
    @JsonSetter("Links")
    public void setLinks(Links links) {
        this.links = links;
    }

    /**
     * Getter for Meta.
     * @return Returns the Meta
     */
    @JsonGetter("Meta")
    public Meta getMeta() {
        return meta;
    }

    /**
     * Setter for Meta.
     * @param meta Value for Meta
     */
    @JsonSetter("Meta")
    public void setMeta(Meta meta) {
        this.meta = meta;
    }

    /**
     * Converts this AccountAccessConsentResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccountAccessConsentResponse [" + "data=" + data + ", risk=" + risk + ", links="
                + links + ", meta=" + meta + "]";
    }

    /**
     * Builds a new {@link AccountAccessConsentResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccountAccessConsentResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(data, risk, links, meta);
        return builder;
    }

    /**
     * Class to build instances of {@link AccountAccessConsentResponse}.
     */
    public static class Builder {
        private AccountAccessConsentResponseModel data;
        private Risk risk;
        private Links links;
        private Meta meta;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  data  AccountAccessConsentResponseModel value for data.
         * @param  risk  Risk value for risk.
         * @param  links  Links value for links.
         * @param  meta  Meta value for meta.
         */
        public Builder(AccountAccessConsentResponseModel data, Risk risk, Links links, Meta meta) {
            this.data = data;
            this.risk = risk;
            this.links = links;
            this.meta = meta;
        }

        /**
         * Setter for data.
         * @param  data  AccountAccessConsentResponseModel value for data.
         * @return Builder
         */
        public Builder data(AccountAccessConsentResponseModel data) {
            this.data = data;
            return this;
        }

        /**
         * Setter for risk.
         * @param  risk  Risk value for risk.
         * @return Builder
         */
        public Builder risk(Risk risk) {
            this.risk = risk;
            return this;
        }

        /**
         * Setter for links.
         * @param  links  Links value for links.
         * @return Builder
         */
        public Builder links(Links links) {
            this.links = links;
            return this;
        }

        /**
         * Setter for meta.
         * @param  meta  Meta value for meta.
         * @return Builder
         */
        public Builder meta(Meta meta) {
            this.meta = meta;
            return this;
        }

        /**
         * Builds a new {@link AccountAccessConsentResponse} object using the set fields.
         * @return {@link AccountAccessConsentResponse}
         */
        public AccountAccessConsentResponse build() {
            return new AccountAccessConsentResponse(data, risk, links, meta);
        }
    }
}
