/*
 * AccountAndTransactionAPISpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.co.middleware.apicentre.apinomatls.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for AccountResponseData type.
 */
public class AccountResponseData {
    private List<AccountModel> account;

    /**
     * Default constructor.
     */
    public AccountResponseData() {
    }

    /**
     * Initialization constructor.
     * @param  account  List of AccountModel value for account.
     */
    public AccountResponseData(
            List<AccountModel> account) {
        this.account = account;
    }

    /**
     * Getter for Account.
     * Account
     * @return Returns the List of AccountModel
     */
    @JsonGetter("Account")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<AccountModel> getAccount() {
        return account;
    }

    /**
     * Setter for Account.
     * Account
     * @param account Value for List of AccountModel
     */
    @JsonSetter("Account")
    public void setAccount(List<AccountModel> account) {
        this.account = account;
    }

    /**
     * Converts this AccountResponseData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccountResponseData [" + "account=" + account + "]";
    }

    /**
     * Builds a new {@link AccountResponseData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccountResponseData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .account(getAccount());
        return builder;
    }

    /**
     * Class to build instances of {@link AccountResponseData}.
     */
    public static class Builder {
        private List<AccountModel> account;



        /**
         * Setter for account.
         * @param  account  List of AccountModel value for account.
         * @return Builder
         */
        public Builder account(List<AccountModel> account) {
            this.account = account;
            return this;
        }

        /**
         * Builds a new {@link AccountResponseData} object using the set fields.
         * @return {@link AccountResponseData}
         */
        public AccountResponseData build() {
            return new AccountResponseData(account);
        }
    }
}
