/*
 * AccountAndTransactionAPISpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.co.middleware.apicentre.apinomatls.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for BalancesResponseData type.
 */
public class BalancesResponseData {
    private List<BalanceModel> balance;

    /**
     * Default constructor.
     */
    public BalancesResponseData() {
    }

    /**
     * Initialization constructor.
     * @param  balance  List of BalanceModel value for balance.
     */
    public BalancesResponseData(
            List<BalanceModel> balance) {
        this.balance = balance;
    }

    /**
     * Getter for Balance.
     * Balance
     * @return Returns the List of BalanceModel
     */
    @JsonGetter("Balance")
    public List<BalanceModel> getBalance() {
        return balance;
    }

    /**
     * Setter for Balance.
     * Balance
     * @param balance Value for List of BalanceModel
     */
    @JsonSetter("Balance")
    public void setBalance(List<BalanceModel> balance) {
        this.balance = balance;
    }

    /**
     * Converts this BalancesResponseData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BalancesResponseData [" + "balance=" + balance + "]";
    }

    /**
     * Builds a new {@link BalancesResponseData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BalancesResponseData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(balance);
        return builder;
    }

    /**
     * Class to build instances of {@link BalancesResponseData}.
     */
    public static class Builder {
        private List<BalanceModel> balance;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  balance  List of BalanceModel value for balance.
         */
        public Builder(List<BalanceModel> balance) {
            this.balance = balance;
        }

        /**
         * Setter for balance.
         * @param  balance  List of BalanceModel value for balance.
         * @return Builder
         */
        public Builder balance(List<BalanceModel> balance) {
            this.balance = balance;
            return this;
        }

        /**
         * Builds a new {@link BalancesResponseData} object using the set fields.
         * @return {@link BalancesResponseData}
         */
        public BalancesResponseData build() {
            return new BalancesResponseData(balance);
        }
    }
}
