/*
 * AccountAndTransactionAPISpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.co.middleware.apicentre.apinomatls.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * CardSchemeNameEnum to be used.
 */
public enum CardSchemeNameEnum {
    AMERICANEXPRESS,

    DINERS,

    DISCOVER,

    MASTERCARD,

    VISA;


    private static TreeMap<String, CardSchemeNameEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        AMERICANEXPRESS.value = "AmericanExpress";
        DINERS.value = "Diners";
        DISCOVER.value = "Discover";
        MASTERCARD.value = "MasterCard";
        VISA.value = "VISA";

        valueMap.put("AmericanExpress", AMERICANEXPRESS);
        valueMap.put("Diners", DINERS);
        valueMap.put("Discover", DISCOVER);
        valueMap.put("MasterCard", MASTERCARD);
        valueMap.put("VISA", VISA);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static CardSchemeNameEnum constructFromString(String toConvert) throws IOException {
        CardSchemeNameEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static CardSchemeNameEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of CardSchemeNameEnum values to list of string values.
     * @param toConvert The list of CardSchemeNameEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<CardSchemeNameEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (CardSchemeNameEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 