/*
 * AccountAndTransactionAPISpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.co.middleware.apicentre.apinomatls.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for GeoLocation type.
 */
public class GeoLocation {
    private String latitude;
    private String longitude;

    /**
     * Default constructor.
     */
    public GeoLocation() {
    }

    /**
     * Initialization constructor.
     * @param  latitude  String value for latitude.
     * @param  longitude  String value for longitude.
     */
    public GeoLocation(
            String latitude,
            String longitude) {
        this.latitude = latitude;
        this.longitude = longitude;
    }

    /**
     * Getter for Latitude.
     * Latitude measured in decimal degress
     * @return Returns the String
     */
    @JsonGetter("Latitude")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLatitude() {
        return latitude;
    }

    /**
     * Setter for Latitude.
     * Latitude measured in decimal degress
     * @param latitude Value for String
     */
    @JsonSetter("Latitude")
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    /**
     * Getter for Longitude.
     * Longitude measured in decimal degress
     * @return Returns the String
     */
    @JsonGetter("Longitude")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLongitude() {
        return longitude;
    }

    /**
     * Setter for Longitude.
     * Longitude measured in decimal degress
     * @param longitude Value for String
     */
    @JsonSetter("Longitude")
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    /**
     * Converts this GeoLocation into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GeoLocation [" + "latitude=" + latitude + ", longitude=" + longitude + "]";
    }

    /**
     * Builds a new {@link GeoLocation.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GeoLocation.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .latitude(getLatitude())
                .longitude(getLongitude());
        return builder;
    }

    /**
     * Class to build instances of {@link GeoLocation}.
     */
    public static class Builder {
        private String latitude;
        private String longitude;



        /**
         * Setter for latitude.
         * @param  latitude  String value for latitude.
         * @return Builder
         */
        public Builder latitude(String latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * Setter for longitude.
         * @param  longitude  String value for longitude.
         * @return Builder
         */
        public Builder longitude(String longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * Builds a new {@link GeoLocation} object using the set fields.
         * @return {@link GeoLocation}
         */
        public GeoLocation build() {
            return new GeoLocation(latitude, longitude);
        }
    }
}
