/*
 * AccountAndTransactionAPISpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.co.middleware.apicentre.apinomatls.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for GetAccountStatementTransactionsResponseData type.
 */
public class GetAccountStatementTransactionsResponseData {
    private List<TransactionModel> transaction;

    /**
     * Default constructor.
     */
    public GetAccountStatementTransactionsResponseData() {
    }

    /**
     * Initialization constructor.
     * @param  transaction  List of TransactionModel value for transaction.
     */
    public GetAccountStatementTransactionsResponseData(
            List<TransactionModel> transaction) {
        this.transaction = transaction;
    }

    /**
     * Getter for Transaction.
     * Provides further details on an entry in the report.
     * @return Returns the List of TransactionModel
     */
    @JsonGetter("Transaction")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<TransactionModel> getTransaction() {
        return transaction;
    }

    /**
     * Setter for Transaction.
     * Provides further details on an entry in the report.
     * @param transaction Value for List of TransactionModel
     */
    @JsonSetter("Transaction")
    public void setTransaction(List<TransactionModel> transaction) {
        this.transaction = transaction;
    }

    /**
     * Converts this GetAccountStatementTransactionsResponseData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GetAccountStatementTransactionsResponseData [" + "transaction=" + transaction + "]";
    }

    /**
     * Builds a new {@link GetAccountStatementTransactionsResponseData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GetAccountStatementTransactionsResponseData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .transaction(getTransaction());
        return builder;
    }

    /**
     * Class to build instances of {@link GetAccountStatementTransactionsResponseData}.
     */
    public static class Builder {
        private List<TransactionModel> transaction;



        /**
         * Setter for transaction.
         * @param  transaction  List of TransactionModel value for transaction.
         * @return Builder
         */
        public Builder transaction(List<TransactionModel> transaction) {
            this.transaction = transaction;
            return this;
        }

        /**
         * Builds a new {@link GetAccountStatementTransactionsResponseData} object using the set
         * fields.
         * @return {@link GetAccountStatementTransactionsResponseData}
         */
        public GetAccountStatementTransactionsResponseData build() {
            return new GetAccountStatementTransactionsResponseData(transaction);
        }
    }
}
