/*
 * AccountAndTransactionAPISpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.co.middleware.apicentre.apinomatls.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for GetOffersResponseData type.
 */
public class GetOffersResponseData {
    private List<OfferModel> offer;

    /**
     * Default constructor.
     */
    public GetOffersResponseData() {
    }

    /**
     * Initialization constructor.
     * @param  offer  List of OfferModel value for offer.
     */
    public GetOffersResponseData(
            List<OfferModel> offer) {
        this.offer = offer;
    }

    /**
     * Getter for Offer.
     * @return Returns the List of OfferModel
     */
    @JsonGetter("Offer")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<OfferModel> getOffer() {
        return offer;
    }

    /**
     * Setter for Offer.
     * @param offer Value for List of OfferModel
     */
    @JsonSetter("Offer")
    public void setOffer(List<OfferModel> offer) {
        this.offer = offer;
    }

    /**
     * Converts this GetOffersResponseData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GetOffersResponseData [" + "offer=" + offer + "]";
    }

    /**
     * Builds a new {@link GetOffersResponseData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GetOffersResponseData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .offer(getOffer());
        return builder;
    }

    /**
     * Class to build instances of {@link GetOffersResponseData}.
     */
    public static class Builder {
        private List<OfferModel> offer;



        /**
         * Setter for offer.
         * @param  offer  List of OfferModel value for offer.
         * @return Builder
         */
        public Builder offer(List<OfferModel> offer) {
            this.offer = offer;
            return this;
        }

        /**
         * Builds a new {@link GetOffersResponseData} object using the set fields.
         * @return {@link GetOffersResponseData}
         */
        public GetOffersResponseData build() {
            return new GetOffersResponseData(offer);
        }
    }
}
