/*
 * AccountAndTransactionAPISpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.co.middleware.apicentre.apinomatls.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for GetStatementsResponseData type.
 */
public class GetStatementsResponseData {
    private List<StatementModel> statement;

    /**
     * Default constructor.
     */
    public GetStatementsResponseData() {
    }

    /**
     * Initialization constructor.
     * @param  statement  List of StatementModel value for statement.
     */
    public GetStatementsResponseData(
            List<StatementModel> statement) {
        this.statement = statement;
    }

    /**
     * Getter for Statement.
     * Provides further details on a statement.
     * @return Returns the List of StatementModel
     */
    @JsonGetter("Statement")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<StatementModel> getStatement() {
        return statement;
    }

    /**
     * Setter for Statement.
     * Provides further details on a statement.
     * @param statement Value for List of StatementModel
     */
    @JsonSetter("Statement")
    public void setStatement(List<StatementModel> statement) {
        this.statement = statement;
    }

    /**
     * Converts this GetStatementsResponseData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "GetStatementsResponseData [" + "statement=" + statement + "]";
    }

    /**
     * Builds a new {@link GetStatementsResponseData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link GetStatementsResponseData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .statement(getStatement());
        return builder;
    }

    /**
     * Class to build instances of {@link GetStatementsResponseData}.
     */
    public static class Builder {
        private List<StatementModel> statement;



        /**
         * Setter for statement.
         * @param  statement  List of StatementModel value for statement.
         * @return Builder
         */
        public Builder statement(List<StatementModel> statement) {
            this.statement = statement;
            return this;
        }

        /**
         * Builds a new {@link GetStatementsResponseData} object using the set fields.
         * @return {@link GetStatementsResponseData}
         */
        public GetStatementsResponseData build() {
            return new GetStatementsResponseData(statement);
        }
    }
}
