/*
 * AccountAndTransactionAPISpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.co.middleware.apicentre.apinomatls.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Links type.
 */
public class Links {
    private String self;
    private String first;
    private String prev;
    private String next;
    private String last;

    /**
     * Default constructor.
     */
    public Links() {
    }

    /**
     * Initialization constructor.
     * @param  self  String value for self.
     * @param  first  String value for first.
     * @param  prev  String value for prev.
     * @param  next  String value for next.
     * @param  last  String value for last.
     */
    public Links(
            String self,
            String first,
            String prev,
            String next,
            String last) {
        this.self = self;
        this.first = first;
        this.prev = prev;
        this.next = next;
        this.last = last;
    }

    /**
     * Getter for Self.
     * @return Returns the String
     */
    @JsonGetter("Self")
    public String getSelf() {
        return self;
    }

    /**
     * Setter for Self.
     * @param self Value for String
     */
    @JsonSetter("Self")
    public void setSelf(String self) {
        this.self = self;
    }

    /**
     * Getter for First.
     * @return Returns the String
     */
    @JsonGetter("First")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFirst() {
        return first;
    }

    /**
     * Setter for First.
     * @param first Value for String
     */
    @JsonSetter("First")
    public void setFirst(String first) {
        this.first = first;
    }

    /**
     * Getter for Prev.
     * @return Returns the String
     */
    @JsonGetter("Prev")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPrev() {
        return prev;
    }

    /**
     * Setter for Prev.
     * @param prev Value for String
     */
    @JsonSetter("Prev")
    public void setPrev(String prev) {
        this.prev = prev;
    }

    /**
     * Getter for Next.
     * @return Returns the String
     */
    @JsonGetter("Next")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getNext() {
        return next;
    }

    /**
     * Setter for Next.
     * @param next Value for String
     */
    @JsonSetter("Next")
    public void setNext(String next) {
        this.next = next;
    }

    /**
     * Getter for Last.
     * @return Returns the String
     */
    @JsonGetter("Last")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLast() {
        return last;
    }

    /**
     * Setter for Last.
     * @param last Value for String
     */
    @JsonSetter("Last")
    public void setLast(String last) {
        this.last = last;
    }

    /**
     * Converts this Links into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Links [" + "self=" + self + ", first=" + first + ", prev=" + prev + ", next=" + next
                + ", last=" + last + "]";
    }

    /**
     * Builds a new {@link Links.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Links.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(self)
                .first(getFirst())
                .prev(getPrev())
                .next(getNext())
                .last(getLast());
        return builder;
    }

    /**
     * Class to build instances of {@link Links}.
     */
    public static class Builder {
        private String self;
        private String first;
        private String prev;
        private String next;
        private String last;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  self  String value for self.
         */
        public Builder(String self) {
            this.self = self;
        }

        /**
         * Setter for self.
         * @param  self  String value for self.
         * @return Builder
         */
        public Builder self(String self) {
            this.self = self;
            return this;
        }

        /**
         * Setter for first.
         * @param  first  String value for first.
         * @return Builder
         */
        public Builder first(String first) {
            this.first = first;
            return this;
        }

        /**
         * Setter for prev.
         * @param  prev  String value for prev.
         * @return Builder
         */
        public Builder prev(String prev) {
            this.prev = prev;
            return this;
        }

        /**
         * Setter for next.
         * @param  next  String value for next.
         * @return Builder
         */
        public Builder next(String next) {
            this.next = next;
            return this;
        }

        /**
         * Setter for last.
         * @param  last  String value for last.
         * @return Builder
         */
        public Builder last(String last) {
            this.last = last;
            return this;
        }

        /**
         * Builds a new {@link Links} object using the set fields.
         * @return {@link Links}
         */
        public Links build() {
            return new Links(self, first, prev, next, last);
        }
    }
}
