/*
 * AccountAndTransactionAPISpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.co.middleware.apicentre.apinomatls.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for MerchantDetails type.
 */
public class MerchantDetails {
    private String merchantName;
    private String merchantCategoryCode;

    /**
     * Default constructor.
     */
    public MerchantDetails() {
    }

    /**
     * Initialization constructor.
     * @param  merchantName  String value for merchantName.
     * @param  merchantCategoryCode  String value for merchantCategoryCode.
     */
    public MerchantDetails(
            String merchantName,
            String merchantCategoryCode) {
        this.merchantName = merchantName;
        this.merchantCategoryCode = merchantCategoryCode;
    }

    /**
     * Getter for MerchantName.
     * Name by which the merchant is known.
     * @return Returns the String
     */
    @JsonGetter("MerchantName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * Setter for MerchantName.
     * Name by which the merchant is known.
     * @param merchantName Value for String
     */
    @JsonSetter("MerchantName")
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName;
    }

    /**
     * Getter for MerchantCategoryCode.
     * Category code conform to ISO 18245, related to the type of services or goods the merchant
     * provides for the transaction.
     * @return Returns the String
     */
    @JsonGetter("MerchantCategoryCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMerchantCategoryCode() {
        return merchantCategoryCode;
    }

    /**
     * Setter for MerchantCategoryCode.
     * Category code conform to ISO 18245, related to the type of services or goods the merchant
     * provides for the transaction.
     * @param merchantCategoryCode Value for String
     */
    @JsonSetter("MerchantCategoryCode")
    public void setMerchantCategoryCode(String merchantCategoryCode) {
        this.merchantCategoryCode = merchantCategoryCode;
    }

    /**
     * Converts this MerchantDetails into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MerchantDetails [" + "merchantName=" + merchantName + ", merchantCategoryCode="
                + merchantCategoryCode + "]";
    }

    /**
     * Builds a new {@link MerchantDetails.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MerchantDetails.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .merchantName(getMerchantName())
                .merchantCategoryCode(getMerchantCategoryCode());
        return builder;
    }

    /**
     * Class to build instances of {@link MerchantDetails}.
     */
    public static class Builder {
        private String merchantName;
        private String merchantCategoryCode;



        /**
         * Setter for merchantName.
         * @param  merchantName  String value for merchantName.
         * @return Builder
         */
        public Builder merchantName(String merchantName) {
            this.merchantName = merchantName;
            return this;
        }

        /**
         * Setter for merchantCategoryCode.
         * @param  merchantCategoryCode  String value for merchantCategoryCode.
         * @return Builder
         */
        public Builder merchantCategoryCode(String merchantCategoryCode) {
            this.merchantCategoryCode = merchantCategoryCode;
            return this;
        }

        /**
         * Builds a new {@link MerchantDetails} object using the set fields.
         * @return {@link MerchantDetails}
         */
        public MerchantDetails build() {
            return new MerchantDetails(merchantName, merchantCategoryCode);
        }
    }
}
