/*
 * AccountAndTransactionAPISpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.co.middleware.apicentre.apinomatls.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * PaymentContextCodeEnum to be used.
 */
public enum PaymentContextCodeEnum {
    BILLPAYMENT,

    ECOMMERCEGOODS,

    ECOMMERCESERVICES,

    OTHER,

    PERSONTOPERSON;


    private static TreeMap<String, PaymentContextCodeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        BILLPAYMENT.value = "BillPayment";
        ECOMMERCEGOODS.value = "EcommerceGoods";
        ECOMMERCESERVICES.value = "EcommerceServices";
        OTHER.value = "Other";
        PERSONTOPERSON.value = "PersonToPerson";

        valueMap.put("BillPayment", BILLPAYMENT);
        valueMap.put("EcommerceGoods", ECOMMERCEGOODS);
        valueMap.put("EcommerceServices", ECOMMERCESERVICES);
        valueMap.put("Other", OTHER);
        valueMap.put("PersonToPerson", PERSONTOPERSON);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static PaymentContextCodeEnum constructFromString(String toConvert) throws IOException {
        PaymentContextCodeEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static PaymentContextCodeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PaymentContextCodeEnum values to list of string values.
     * @param toConvert The list of PaymentContextCodeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<PaymentContextCodeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (PaymentContextCodeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 