/*
 * AccountAndTransactionAPISpecificationLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package nz.co.middleware.apicentre.apinomatls.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import java.time.LocalDateTime;
import nz.co.middleware.apicentre.apinomatls.DateTimeHelper;

/**
 * This is a model class for ScheduledPaymentModel type.
 */
public class ScheduledPaymentModel {
    private String accountId;
    private String scheduledPaymentId;
    private LocalDateTime scheduledPaymentDateTime;
    private ScheduledTypeEnum scheduledType;
    private InstructedAmount instructedAmount;
    private Reference reference;
    private CreditorAgent creditorAgent;
    private CreditorAccount creditorAccount;

    /**
     * Default constructor.
     */
    public ScheduledPaymentModel() {
    }

    /**
     * Initialization constructor.
     * @param  accountId  String value for accountId.
     * @param  scheduledPaymentDateTime  LocalDateTime value for scheduledPaymentDateTime.
     * @param  scheduledType  ScheduledTypeEnum value for scheduledType.
     * @param  instructedAmount  InstructedAmount value for instructedAmount.
     * @param  scheduledPaymentId  String value for scheduledPaymentId.
     * @param  reference  Reference value for reference.
     * @param  creditorAgent  CreditorAgent value for creditorAgent.
     * @param  creditorAccount  CreditorAccount value for creditorAccount.
     */
    public ScheduledPaymentModel(
            String accountId,
            LocalDateTime scheduledPaymentDateTime,
            ScheduledTypeEnum scheduledType,
            InstructedAmount instructedAmount,
            String scheduledPaymentId,
            Reference reference,
            CreditorAgent creditorAgent,
            CreditorAccount creditorAccount) {
        this.accountId = accountId;
        this.scheduledPaymentId = scheduledPaymentId;
        this.scheduledPaymentDateTime = scheduledPaymentDateTime;
        this.scheduledType = scheduledType;
        this.instructedAmount = instructedAmount;
        this.reference = reference;
        this.creditorAgent = creditorAgent;
        this.creditorAccount = creditorAccount;
    }

    /**
     * Getter for AccountId.
     * A unique and immutable identifier used to identify the account resource. This identifier has
     * no meaning to the account owner.
     * @return Returns the String
     */
    @JsonGetter("AccountId")
    public String getAccountId() {
        return accountId;
    }

    /**
     * Setter for AccountId.
     * A unique and immutable identifier used to identify the account resource. This identifier has
     * no meaning to the account owner.
     * @param accountId Value for String
     */
    @JsonSetter("AccountId")
    public void setAccountId(String accountId) {
        this.accountId = accountId;
    }

    /**
     * Getter for ScheduledPaymentId.
     * A unique and immutable identifier used to identify the scheduled payment resource. This
     * identifier has no meaning to the account owner.
     * @return Returns the String
     */
    @JsonGetter("ScheduledPaymentId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getScheduledPaymentId() {
        return scheduledPaymentId;
    }

    /**
     * Setter for ScheduledPaymentId.
     * A unique and immutable identifier used to identify the scheduled payment resource. This
     * identifier has no meaning to the account owner.
     * @param scheduledPaymentId Value for String
     */
    @JsonSetter("ScheduledPaymentId")
    public void setScheduledPaymentId(String scheduledPaymentId) {
        this.scheduledPaymentId = scheduledPaymentId;
    }

    /**
     * Getter for ScheduledPaymentDateTime.
     * The date on which the scheduled payment will be made. All dates in the JSON payloads are
     * represented in ISO 8601 date-time format. All date-time fields in responses must include the
     * timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @return Returns the LocalDateTime
     */
    @JsonGetter("ScheduledPaymentDateTime")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getScheduledPaymentDateTime() {
        return scheduledPaymentDateTime;
    }

    /**
     * Setter for ScheduledPaymentDateTime.
     * The date on which the scheduled payment will be made. All dates in the JSON payloads are
     * represented in ISO 8601 date-time format. All date-time fields in responses must include the
     * timezone. An example is below: 2017-04-05T10:43:07+00:00
     * @param scheduledPaymentDateTime Value for LocalDateTime
     */
    @JsonSetter("ScheduledPaymentDateTime")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setScheduledPaymentDateTime(LocalDateTime scheduledPaymentDateTime) {
        this.scheduledPaymentDateTime = scheduledPaymentDateTime;
    }

    /**
     * Getter for ScheduledType.
     * Specifies the scheduled payment date type requested
     * @return Returns the ScheduledTypeEnum
     */
    @JsonGetter("ScheduledType")
    public ScheduledTypeEnum getScheduledType() {
        return scheduledType;
    }

    /**
     * Setter for ScheduledType.
     * Specifies the scheduled payment date type requested
     * @param scheduledType Value for ScheduledTypeEnum
     */
    @JsonSetter("ScheduledType")
    public void setScheduledType(ScheduledTypeEnum scheduledType) {
        this.scheduledType = scheduledType;
    }

    /**
     * Getter for InstructedAmount.
     * Amount of money of the cash balance after a transaction entry is applied to the account..
     * @return Returns the InstructedAmount
     */
    @JsonGetter("InstructedAmount")
    public InstructedAmount getInstructedAmount() {
        return instructedAmount;
    }

    /**
     * Setter for InstructedAmount.
     * Amount of money of the cash balance after a transaction entry is applied to the account..
     * @param instructedAmount Value for InstructedAmount
     */
    @JsonSetter("InstructedAmount")
    public void setInstructedAmount(InstructedAmount instructedAmount) {
        this.instructedAmount = instructedAmount;
    }

    /**
     * Getter for Reference.
     * @return Returns the Reference
     */
    @JsonGetter("Reference")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Reference getReference() {
        return reference;
    }

    /**
     * Setter for Reference.
     * @param reference Value for Reference
     */
    @JsonSetter("Reference")
    public void setReference(Reference reference) {
        this.reference = reference;
    }

    /**
     * Getter for CreditorAgent.
     * Party that manages the account on behalf of the account owner, that is manages the
     * registration and booking of entries on the account, calculates balances on the account and
     * provides information about the account. This is the servicer of the beneficiary account.
     * @return Returns the CreditorAgent
     */
    @JsonGetter("CreditorAgent")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CreditorAgent getCreditorAgent() {
        return creditorAgent;
    }

    /**
     * Setter for CreditorAgent.
     * Party that manages the account on behalf of the account owner, that is manages the
     * registration and booking of entries on the account, calculates balances on the account and
     * provides information about the account. This is the servicer of the beneficiary account.
     * @param creditorAgent Value for CreditorAgent
     */
    @JsonSetter("CreditorAgent")
    public void setCreditorAgent(CreditorAgent creditorAgent) {
        this.creditorAgent = creditorAgent;
    }

    /**
     * Getter for CreditorAccount.
     * Unambiguous identification of the account of the creditor, in the case of a debit
     * transaction.
     * @return Returns the CreditorAccount
     */
    @JsonGetter("CreditorAccount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CreditorAccount getCreditorAccount() {
        return creditorAccount;
    }

    /**
     * Setter for CreditorAccount.
     * Unambiguous identification of the account of the creditor, in the case of a debit
     * transaction.
     * @param creditorAccount Value for CreditorAccount
     */
    @JsonSetter("CreditorAccount")
    public void setCreditorAccount(CreditorAccount creditorAccount) {
        this.creditorAccount = creditorAccount;
    }

    /**
     * Converts this ScheduledPaymentModel into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ScheduledPaymentModel [" + "accountId=" + accountId + ", scheduledPaymentDateTime="
                + scheduledPaymentDateTime + ", scheduledType=" + scheduledType
                + ", instructedAmount=" + instructedAmount + ", scheduledPaymentId="
                + scheduledPaymentId + ", reference=" + reference + ", creditorAgent="
                + creditorAgent + ", creditorAccount=" + creditorAccount + "]";
    }

    /**
     * Builds a new {@link ScheduledPaymentModel.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ScheduledPaymentModel.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(accountId, scheduledPaymentDateTime, scheduledType,
                instructedAmount)
                .scheduledPaymentId(getScheduledPaymentId())
                .reference(getReference())
                .creditorAgent(getCreditorAgent())
                .creditorAccount(getCreditorAccount());
        return builder;
    }

    /**
     * Class to build instances of {@link ScheduledPaymentModel}.
     */
    public static class Builder {
        private String accountId;
        private LocalDateTime scheduledPaymentDateTime;
        private ScheduledTypeEnum scheduledType;
        private InstructedAmount instructedAmount;
        private String scheduledPaymentId;
        private Reference reference;
        private CreditorAgent creditorAgent;
        private CreditorAccount creditorAccount;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  accountId  String value for accountId.
         * @param  scheduledPaymentDateTime  LocalDateTime value for scheduledPaymentDateTime.
         * @param  scheduledType  ScheduledTypeEnum value for scheduledType.
         * @param  instructedAmount  InstructedAmount value for instructedAmount.
         */
        public Builder(String accountId, LocalDateTime scheduledPaymentDateTime,
                ScheduledTypeEnum scheduledType, InstructedAmount instructedAmount) {
            this.accountId = accountId;
            this.scheduledPaymentDateTime = scheduledPaymentDateTime;
            this.scheduledType = scheduledType;
            this.instructedAmount = instructedAmount;
        }

        /**
         * Setter for accountId.
         * @param  accountId  String value for accountId.
         * @return Builder
         */
        public Builder accountId(String accountId) {
            this.accountId = accountId;
            return this;
        }

        /**
         * Setter for scheduledPaymentDateTime.
         * @param  scheduledPaymentDateTime  LocalDateTime value for scheduledPaymentDateTime.
         * @return Builder
         */
        public Builder scheduledPaymentDateTime(LocalDateTime scheduledPaymentDateTime) {
            this.scheduledPaymentDateTime = scheduledPaymentDateTime;
            return this;
        }

        /**
         * Setter for scheduledType.
         * @param  scheduledType  ScheduledTypeEnum value for scheduledType.
         * @return Builder
         */
        public Builder scheduledType(ScheduledTypeEnum scheduledType) {
            this.scheduledType = scheduledType;
            return this;
        }

        /**
         * Setter for instructedAmount.
         * @param  instructedAmount  InstructedAmount value for instructedAmount.
         * @return Builder
         */
        public Builder instructedAmount(InstructedAmount instructedAmount) {
            this.instructedAmount = instructedAmount;
            return this;
        }

        /**
         * Setter for scheduledPaymentId.
         * @param  scheduledPaymentId  String value for scheduledPaymentId.
         * @return Builder
         */
        public Builder scheduledPaymentId(String scheduledPaymentId) {
            this.scheduledPaymentId = scheduledPaymentId;
            return this;
        }

        /**
         * Setter for reference.
         * @param  reference  Reference value for reference.
         * @return Builder
         */
        public Builder reference(Reference reference) {
            this.reference = reference;
            return this;
        }

        /**
         * Setter for creditorAgent.
         * @param  creditorAgent  CreditorAgent value for creditorAgent.
         * @return Builder
         */
        public Builder creditorAgent(CreditorAgent creditorAgent) {
            this.creditorAgent = creditorAgent;
            return this;
        }

        /**
         * Setter for creditorAccount.
         * @param  creditorAccount  CreditorAccount value for creditorAccount.
         * @return Builder
         */
        public Builder creditorAccount(CreditorAccount creditorAccount) {
            this.creditorAccount = creditorAccount;
            return this;
        }

        /**
         * Builds a new {@link ScheduledPaymentModel} object using the set fields.
         * @return {@link ScheduledPaymentModel}
         */
        public ScheduledPaymentModel build() {
            return new ScheduledPaymentModel(accountId, scheduledPaymentDateTime, scheduledType,
                    instructedAmount, scheduledPaymentId, reference, creditorAgent,
                    creditorAccount);
        }
    }
}
